client/client/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

client/web/urls.py
from django.urls import path
from .views import (login_user, registerAdvertiser, registerPublisher,
                    index, slots, slot, ad, ads, logout_user, createAd, createSlot,
                    deleteSlot, deleteAd, adCatalog, adDetails, transaction,
                    buyCoins, sellCoins, getAdCoinBalance, getAdForSlot, redirectService)

app_name = 'web'

urlpatterns = [
    path('login/', login_user, name="login_user"),
    path('logout/', logout_user, name="logout_user"),
    path('register/advertiser/', registerAdvertiser, name="register_advertiser"),
    path('register/publisher/', registerPublisher, name="register_publisher"),
    path('ads/', ads, name="myads"),
    path('ad/create', createAd, name="create_ad"),
    path('ad/delete/<int:adid>', deleteAd, name="delete_ad"),
    path('ad/<int:adid>', ad, name="ad"),
    path('slots', slots, name="myslots"),
    path('slot/create', createSlot, name="create_slot"),
    path('slot/delete/<int:slotid>', deleteSlot, name="delete_slot"),
    path('slot/<int:slotid>', slot, name="slot"),
    path('catalog/', adCatalog, name="ad_catalog"),
    path('ad_detail/<int:adid>', adDetails, name="ad_details"),
    path('transaction/', transaction, name="transaction"),
    path('buycoins/', buyCoins, name="buy_coins"),
    path('sellcoins/', sellCoins, name="sell_coins"),
    path('getbalance/', getAdCoinBalance, name="adcoin_balance"),
    path('getadforslot/<int:slotid>', getAdForSlot, name="get_ad_for_slot"),
    path('redirect/<str:url>', redirectService, name="redirect"),
    path('', index, name='home'),
]

client/web/templates/web/ad.html
{% extends 'web/base_advertiser.html' %}
{% block title %}Ad details{% endblock %}
{% block myads_active %}active{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="container-fluid card" style="margin-top: 1em">
                    <img class="card-img-top img-fluid" src="{{ ad.image }}" style="margin-top: 1em">
                    <h3 class="card-title">{{ ad.name }}</h3>
                    <strong><em>{{ ad.targetUrl }}</em></strong>
                    <div class="card-body">
                        <p>
                            Description: {{ ad.description }}<br>
                            Dimensions: {{ ad.widthPx }} x {{ ad.heightPx }}<br>
                            Cost: {{ ad.maxCost }}
                        </p>
                    </div>
                    <div class="card-footer">
                        <button
                            class="btn btn-danger"
                            data-toggle="modal"
                            data-target="#deleteModal"
                            title="Delete record" id="del">
                        <i class="fa fa-trash"></i>
                    </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Confirmation</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this record?</p>
          </div>
          <div class="modal-footer">
            <a href="{% url 'web:delete_ad' ad.advertisementId %}"><button type="button" class="btn btn-danger" id="delcnf">Yes</button></a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
</div>
{% endblock %}

client/web/templates/web/ad_catalog.html
{% extends 'web/base_publisher.html' %}
{% block title %}Home{% endblock %}
{% block catalog_active %}active{% endblock %}
{% block body %}

    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Available Ads</h3>
            </div>
            <div class="container-fluid">
                {% if ads %}
                    {% for ad in ads %}
                        <div class="col-sm-4 col-lg-2">
                            <div class="card">
                                <a href="#">
                                    <img src="{{ ad.image }}" class="card-img-top img-fluid">
                                </a>
                                <div class="card-body">
                                    <h5 class="card-title">
                                        {{ ad.name }}
                                    </h5>
                                    <p class="card-text">
                                        Description: {{ ad.description }}<br>
                                        Target URL: {{ ad.targetUrl }}<br>
                                        Dim: {{ ad.widthPx }} x {{ ad.heightPx }}<br>
                                    </p>
                                    <a class="btn btn-primary" href="{% url 'web:ad_details' ad.advertisementId %}">Details</a>
                                </div>
                            </div>
                        </div>
                        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

client/web/templates/web/ad_details.html
{% extends 'web/base_publisher.html' %}
{% block title %}Ad details{% endblock %}
{% block catalog_active %}active{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="container-fluid card" style="margin-top: 1em">
                    <img class="card-img-top img-fluid" src="{{ ad.image }}" style="margin-top: 1em">
                    <h3 class="card-title">{{ ad.name }}</h3>
                    <strong><em>{{ ad.targetUrl }}</em></strong>
                    <div class="card-body">
                        <p>
                            Description: {{ ad.description }}<br>
                            Dimensions: {{ ad.widthPx }} x {{ ad.heightPx }}<br>
                            Cost: {{ ad.maxCost }}
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="container-fluid card" style="margin-top: 1em">
                    <div class="card-body">
                        <form class="form-horizontal" role="form" action="{% url 'web:transaction' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="slotid">
                                Slot ID:
                            </label>
                            <div class="col-sm-10">
                                <input id="slotid" maxlength="30" name="slotid" type="text">
                            </div>
                        </div>
                            <input type="hidden" name="adid" value="{{ ad.advertisementId }}">
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

client/web/templates/web/base_publisher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Web Advertising{% endblock %}</title>
    {# Loading the static files #}
    {% load staticfiles %}
    {# The custom css file to load #}
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    {# The navbar, https://getbootstrap.com/docs/4.0/components/navbar/  #}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Web Advertising</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="nav-pills navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link {% block slots_active %}{% endblock %}" href="{% url 'web:myslots' %}">My slots</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link {% block create_active %}{% endblock %}" href="{% url 'web:create_slot' %}">Create slots</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link {% block catalog_active %}{% endblock %}" href="{% url 'web:ad_catalog' %}">Catalog</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link {% block coins_active %}{% endblock %}" href="{% url 'web:sell_coins' %}">Sell AdCoins</a>
                </li>
            </ul>
            <ul class="nav-pills navbar-nav mr-auto"></ul>
            <ul class="nav-pills navbar-nav">
                {% if request.user.is_authenticated == 0 %}
                    <li class="nav-item active">
                        <a class="nav-link active" href="{% url 'web:login_user' %}"><i class="fa fa-power-off"></i>&nbsp; Log In</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link bg-success"><div id="balance"></div></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'web:logout_user' %}"><i class="fa fa-power-off"></i>&nbsp; Log out</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js_scripts %}
    <script>
        $.ajax({
            url: "http://10.100.54.62:8000/getbalance/",
            type: 'GET',
            dataType: 'json', // added data type
            success: function(res) {
                console.log(res);
                $("#balance").append("AdCoins: " + res);
            }
        });
    </script>
{% endblock %}
</html>

client/web/templates/web/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Web Advertising{% endblock %}</title>
    {# Loading the static files #}
    {% load staticfiles %}
    {# The custom css file to load #}
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    {# The navbar, https://getbootstrap.com/docs/4.0/components/navbar/  #}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Web Advertising</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="nav-pills navbar-nav mr-auto"></ul>
            <ul class="nav-pills navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link {% block register_advertiser_active%}{% endblock %}" href="{% url 'web:register_advertiser' %}"><i class="fa fa-user"></i>&nbsp; Register as Advertiser</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link {% block register_publisher_active%}{% endblock %}" href="{% url 'web:register_publisher' %}"><i class="fa fa-user"></i>&nbsp; Register as Publisher</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link {% block login_active%}{% endblock %}" href="{% url 'web:login_user' %}"><i class="fa fa-power-off"></i>&nbsp; Log In</a>
                </li>
            </ul>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js_scripts %}
{% endblock %}
</html>

client/web/templates/web/buy_coins.html
{% extends 'web/base_advertiser.html' %}
{% block title %}Buy Coins{% endblock %}
{% block coins_active %}active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Buy Coins</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'web:buy_coins'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="coins">
                                Coins:
                            </label>
                            <div class="col-sm-10">
                                <input id="coins" maxlength="30" name="coins" type="number">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

client/web/templates/web/create_ad.html
{% extends 'web/base_advertiser.html' %}
{% load bootstrap4 %}
{% block title %}Register{% endblock %}
{% block ad_active %}active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Create Ad</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form role="form" action="{% url 'web:create_ad'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form createform %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

client/web/templates/web/login.html
{% extends 'web/base_visitor.html' %}
{% block title %}Login{% endblock %}
{% block login_active %}active{% endblock %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'web:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

client/web/templates/web/my_ads.html
{% extends 'web/base_advertiser.html' %}
{% block title %}My Ads{% endblock %}
{% block myads_active %}active{% endblock %}
{% block body %}

    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <h3>My Ad Campaigns</h3>
            </div>
            <div class="container-fluid">
                {% if ads %}
                    {% for ad in ads %}
                        <div class="col-sm-4 col-lg-2">
                            <div class="card">
                                <a href="#">
                                    <img src="{{ ad.image }}" class="card-img-top img-fluid">
                                </a>
                                <div class="card-body">
                                    <h5 class="card-title">
                                        {{ ad.name }}
                                    </h5>
                                    <p class="card-text">
                                        Description: {{ ad.description }}<br>
                                        Target URL: {{ ad.targetUrl }}<br>
                                        Dim: {{ ad.widthPx }} x {{ ad.heightPx }}<br>
                                    </p>
                                    <a class="btn btn-primary" href="{% url 'web:ad' ad.advertisementId %}">Details</a>
                                </div>
                            </div>
                        </div>
                        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

client/web/templates/web/my_slots.html
{% extends 'web/base_publisher.html' %}
{% block title %}My Slots{% endblock %}
{% block slots_active %}active{% endblock %}
{% block body %}

    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <h3>My slots</h3>
            </div>
            <div class="container-fluid">
                {% if slots %}
                    {% for slot in slots %}
                        <div class="col-sm-4 col-lg-2">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        {{ slot.website }}
                                    </h5>
                                    <p class="card-text">
                                        On sale: {{ slot.onSale }}<br>
                                        Cost: {{ slot.cost }}<br>
{#                                        Dim: {{ slot.widthPx }} x {{ slot.heightPx }}#}
                                    </p>
                                    <a class="btn btn-primary" href="{% url 'web:slot' slot.slotId %}">Details</a>
                                </div>
                            </div>
                        </div>
                        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

client/web/templates/web/register_advertiser.html
{% extends 'web/base_visitor.html' %}
{% load bootstrap4 %}
{% block title %}Register{% endblock %}
{% block register_advertiser_active %}active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Register</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form role="form" action="{% url 'web:register_advertiser'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form uform %}
                        {% bootstrap_form aform %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    Already have an account? <a href="{% url 'web:login_user' %}">Click here</a> to login!
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

client/web/templates/web/register_publisher.html
{% extends 'web/base_visitor.html' %}
{% load bootstrap4 %}
{% block title %}Register{% endblock %}
{% block register_publisher_active %}active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Register</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form role="form" action="{% url 'web:register_publisher'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form uform %}
                        {% bootstrap_form pform %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    Already have an account? <a href="{% url 'web:login_user' %}">Click here</a> to login!
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

client/web/templates/web/sell_coins.html
{% extends 'web/base_publisher.html' %}
{% block title %}Sell Coins{% endblock %}
{% block coins_active %}active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Sell Coins</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'web:sell_coins'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="coins">
                                Coins:
                            </label>
                            <div class="col-sm-10">
                                <input id="coins" maxlength="30" name="coins" type="number">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

client/web/templates/web/slot.html
{% extends 'web/base_publisher.html' %}
{% block title %}Slot details{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="container-fluid card" style="margin-top: 1em">
                    <h3 class="card-title">{{ slot.website }}</h3>
                    <strong><em>{{ slot.website }}</em></strong>
                    <div class="card-body">
                        <p>
                            Slot ID: {{ slot.slotId }}<br>
                            On Sale: {{ slot.onSale }}<br>
                            Ad verified: {{ slot.verifiedWebsite }}<br>
                            Slot verification: {{ slot.verifiedSlot }}<br>
                            Generated URL: {{ slot.generatedUrl }}<br>
{#                            Dimensions: {{ slot.widthPx }} x {{ slot.heightPx }}<br>#}
                            Cost: {{ slot.cost }}<br>
                        </p>
                    </div>
                    <div class="card-footer">
                        <button
                            class="btn btn-danger"
                            data-toggle="modal"
                            data-target="#deleteModal"
                            title="Delete record" id="del">
                        <i class="fa fa-trash"></i>
                    </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Confirmation</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this record?</p>
          </div>
          <div class="modal-footer">
            <a href="{% url 'web:delete_slot' slot.slotId %}"><button type="button" class="btn btn-danger" id="delcnf">Yes</button></a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}